# Install and configure MySQL
---

- block:
    - dynamic_defaults:
        hostvars: '{{ hostvars[inventory_hostname] }}'
        defaults: '{{ mysql_dynamic_defaults }}'
        must_match: yes

    - assert:
        that:
          - mysql_query_cache_type in mysql_query_cache_types
  tags: [mysql, always]

- block:
    - include: setup-repository-{{ ansible_pkg_mgr }}.yml

    - name: Install MySQL packages
      package: >
        name={{ item }} state=present
      become: yes
      with_items: '{{ mysql_packages }}'
  tags: [mysql, packages]

- block:
    - name: Create MySQL directories
      file: >
        name={{ item }} owner=mysql group=mysql mode=755 state=directory
      with_items:
        - '{{ mysql_log_directory }}'

    # - name: Configure MySQL
    #   template: >
    #     src={{ mysql_config_file }} dest={{ mysql_config_path }} owner=root group=root mode=600
    #   notify: restart mysql

    - name: Configure socket for Debian
      replace: >
        dest=/etc/mysql/debian.cnf owner=root group=root mode=600
        regexp='^socket\s+=\s+\S+' replace='socket = {{ mysql_socket_file }}'
      when: ansible_os_family == 'Debian'

    - name: Remove default MySQL configuration
      file: >
        path=/etc/mysql/{{ item }} state=absent
      notify: restart mysql
      with_items:
        - conf.d/mysql.cnf
        - conf.d/mysqldump.cnf
        - mysql.conf.d/mysqld.cnf
        - mysql.conf.d/mysqld_safe_syslog.cnf

    - name: Copy user my.cnf file with root credentials
      template: >
        src=root.my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
  become: yes
  tags: [mysql, config]

- name: Start MySQL service
  service: >
    name={{ mysql_service }} state=started enabled=yes
  become: yes
  tags: [mysql, services]

- block:
    - meta: flush_handlers

    - name: Configure MySQL root password
      mysql_user: >
        name=root host={{ item }} password={{ mysql_root_password }} check_implicit_admin=yes state=present
      with_items:
        - '{{ ansible_hostname }}'
        - localhost
        - 127.0.0.1
        - ::1

    - name: Remove anonymous MySQL user
      mysql_user: >
        name='' state=absent

    - name: Remove MySQL test database
      mysql_db: >
        name=test state=absent
  become: yes
  tags: [mysql, config]
